create table user (
        id integer generated by default as identity,
        name varchar(255) NOT NULL,
        telephone_Number varchar(32) NOT NULL,
        email varchar(255) NOT NULL,
        address varchar(255),
        password varchar(255) NOT NULL);


INSERT INTO user (name, telephone_Number, email, address, password)
                VALUES('Tomas','+37062452689', 'tomas@gmail.com', 'Vilnius', 'Tomas123!');
INSERT INTO user (name, telephone_Number, email, address, password)
                VALUES('Patrikas','+37062412689', 'patrick@gmail.com', 'Vilnius', 'Patrick123!');
INSERT INTO user (name, telephone_Number, email, address, password)
                VALUES('Justina','+37062454785', 'dzast@gmail.com', 'Radviliskis', 'Justinele123!');